source 'https://rubygems.org'

gem 'rails', '5.2.3'

gem 'loofah', '>= 2.2.3'
gem 'i18n', '1.6.0'
gem 'rails-html-sanitizer', '~> 1.0.4'
gem 'sprockets-rails'

gem 'tzinfo-data'

# Gems used only for assets and not required
# in production environments by default.
gem 'sassc-rails', '~> 2.1', '>= 2.1.1'
gem 'coffee-rails'
gem 'coffee-script'
gem 'coffee-script-source'
gem 'uglifier', '3.0.4'
gem 'therubyrhino'

# use bootstrap4
gem 'bootstrap', '~> 4.3', '>= 4.3.1'

gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'json', '2.1.0'
gem 'json-schema', '1.0.10'

gem "jruby-jars", "= 9.2.6.0"
gem 'atomic', '= 1.0.1'
gem 'unicode-display_width', '~> 1.6'
gem 'rack-test', '~> 1.1.0'

group :test do
  gem 'rspec', "~> 3.6.0"
  gem 'rspec-rails'
  gem 'simplecov', "0.7.1"

  # selenium stuff
  gem "rspec-retry"
  gem "selenium-webdriver", "= 3.6.0"
  gem 'factory_bot', '~> 4.11', '>= 4.11.1'
  gem "parallel_tests", "~> 2.14.0"

  # need access to ActiveSupport for helpers
  gem 'activesupport', '5.2.3'
end

group :development, :test do
  gem 'pry-debugger-jruby'
  gem 'pry-rails'
  gem 'pry-nav'
  gem 'rubocop', '~> 0.54.0', require: false
end

gem 'puma', '~> 3.12', '>= 3.12.1'

gem "net-http-persistent", "2.8"
gem "multipart-post", "1.2.0"
gem 'multi_json', '~> 1.13.1'

gem 'rubyzip', '~> 1.2.2'
gem "zip-zip", "0.3"

gem 'nokogiri', '1.10.3'


require 'asutils'

# Allow plugins to provide their own Gemfiles too.
ASUtils.load_plugin_gems(self)
