source 'https://rubygems.org'

gem 'rails', '5.2.3'

gem 'loofah', '>= 2.2.3'
gem 'i18n', '1.6.0'
gem 'rubyzip', '~> 1.2.2'

gem 'nokogiri', '1.10.3'

gem 'sprockets-rails'

gem 'puma', '~> 3.12', '>= 3.12.1'
gem 'atomic', '= 1.0.1'

# use bootstrap4
gem 'bootstrap', '~> 4.3', '>= 4.3.1'
# Use SCSS for stylesheets
gem 'sassc-rails', '~> 2.1', '>= 2.1.1'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '3.0.4'
# Use font-awesome icons
gem 'font-awesome-sass', '~> 5.8.1'

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails'
# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'therubyrhino'
# Use jquery as the JavaScript library
gem 'jquery-rails'

gem 'json', '2.1.0'
gem 'json-schema', '1.0.10'
gem "net-http-persistent", "2.8"
gem "multipart-post", "1.2.0"
gem 'rack-test', '~> 1.1.0'

# support clipboard
gem 'clipboard-rails'

# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'

# Enable support for `rails server`
gem 'listen', group: :development

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

group :development, :test do
  gem 'pry-debugger-jruby'
  gem 'pry-rails'
  gem 'pry-nav'
  gem 'rubocop', '~> 0.54.0', require: false
end

group :test do
  gem 'rspec', "~> 3.6.0"
  gem "rspec-retry"
  gem 'rspec-rails'
  gem 'rails-controller-testing'
  gem 'simplecov', "0.7.1"
  gem 'factory_bot_rails', '~> 4.11', '>= 4.11.1'
  gem "fog-aws", "2.0.0", :require => false
  gem "selenium-webdriver", "= 3.6.0"
  gem 'capybara', '3.12.0'
  gem 'launchy'
  gem 'axe-matchers'
end
